### ISSUE TITLE
[Java] Test fails due to JSON key order

### ISSUE THREAD

**Issue by asfimport** [apache/arrow-java#228]
While verifying 10.0.1 I came across this java test error that is caused by a mismatch in the ordering of the JSON metadata description (see attached image)

`ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.177 s <<< FAILURE! - in org.apache.arrow.adapter.jdbc.JdbcToArrowCommentMetadataTest`
`[ERROR] org.apache.arrow.adapter.jdbc.JdbcToArrowCommentMetadataTest.schemaCommentWithDatabaseMetadata Time elapsed: 0.141 s <<< FAILURE!`
`org.opentest4j.AssertionFailedError: `

cc @lidavidm  

**Reporter**: [Jacob Wujciak](https://issues.apache.org/jira/browse/ARROW-18385) / @assignUser
#### Original Issue Attachments:
- [image.png](https://issues.apache.org/jira/secure/attachment/13053000/image.png)

<sub>**Note**: *This issue was originally created as [ARROW-18385](https://issues.apache.org/jira/browse/ARROW-18385). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Stale
