### ISSUE TITLE
Transfer the Java related open issues in apache/arrow to apache/arrow-java

### ISSUE THREAD

**Issue by kou** [apache/arrow-java#3]
@assignUser did it for apache/arrow-go.

See also: https://lists.apache.org/thread/nnkfzsqtvwgfoqys4s6hwlf54rw0p8xo

**Comment by kou** [comment]
See also: https://github.com/apache/arrow-go/issues/25

**Comment by assignUser** [comment]
I can do this again, there are roughly 400 open java issue,  I will only exclude the move related issues. I didn't see any other wrongly tagged issues on a glance but we can also always move them back if some are found. 
With 400 issues it probably makes sense to review them all and close stale/outdated ones.

**Comment by assignUser** [comment]
I am running into rate limits so I'll continues this later

**Comment by assignUser** [comment]
Done

**Comment by raulcd** [comment]
@assignUser  could you share the script you use to transfer the issues? Where all the issues with `Component: Java` transferred?

**Comment by assignUser** [comment]
@raulcd  yes here it is:
```bash 
# get the open issues with the label -L has to be set to > then open issues (or what ever batch you want to work on seems like the backend can be a bit tricky when transfering a large number of issues
gh issue list --label "Component: Java" --state "open" -L 400 --json 'number,labels'  > issues.json
jq -r '[.[].number] -  ['<numbers of issues you want to exclude>'] | map(select(. < '<only transfer issues with issue num smaller than ths'>')) | .[]' issues.json |  xargs -I% gh issue transfer % https://github.com/apache/arrow-java
```
> '<only transfer issues with # smaller than ths'>'
For both go and java we already had some issue in apache/arrow dealing with the remnants there, these should ofc stay there, as issue numbers are sequential we can just exclude via lt.

As mentioned above it's important that the labels you want to carry over already exists in the new repo, otherwise the info will be lost.
