### ISSUE TITLE
[Java] Add microbenchmark code to Java

### ISSUE THREAD

**Issue by asfimport** [apache/arrow-java#367]
@animeshtrivedi has done some microbenchmarking with the Java API. Let's consider adding them to the codebase.

**Reporter**: [Li Jin](https://issues.apache.org/jira/browse/ARROW-3496) / @icexelloss
#### Related issues:
- [[Java] Add micro-benchmarks for Float8Vector and allocators](https://github.com/apache/arrow/issues/16746) (is a parent of)
- [[Java] Add performance benchmarks from SQL workloads](https://github.com/apache/arrow/issues/21684) (is a parent of)
- [[Java] Provide light-weight arrow APIs](https://github.com/apache/arrow/issues/21675) (is related to)

<sub>**Note**: *This issue was originally created as [ARROW-3496](https://issues.apache.org/jira/browse/ARROW-3496). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by assignUser** [comment]
Stale, there are java benchmarks.
