### ISSUE TITLE
[Java] Add ORC JNI related components to travis CI

### ISSUE THREAD

**Issue by asfimport** [apache/arrow-java#409]
**Reporter**: [Yurui Zhou](https://issues.apache.org/jira/browse/ARROW-5519) / @yuruiz

<sub>**Note**: *This issue was originally created as [ARROW-5519](https://issues.apache.org/jira/browse/ARROW-5519). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by lidavidm** [comment]
We no longer have Travis CI.
