### ISSUE TITLE
Disable Maven RAT check in favor of pre-commit one

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow-java#436]
### Describe the enhancement requested

We have two separate RAT checks now, one run during the build and one done via pre-commit. IMO, we should only use the pre-commit one. The build-time RAT check doesn't share config and it is annoying to have the build interrupted during development.

**Comment by kou** [comment]
Oh, sorry.
I missed this.

**Comment by lidavidm** [comment]
Nah, I forgot about this check too until I ran into it today :grimacing: 

For somewhat similar reasons I'm not sure if we'd want to keep Spotless (in Maven) or run google-java-format via pre-commit

**Comment by kou** [comment]
Ah, Spotless isn't a formatter. (I thought that it's a Java formatter.)
We may want to unify all formatters/linters/... to pre-commit.
