### ISSUE TITLE
Modules aren't properly declared

### ISSUE THREAD

**Issue by lidavidm** [apache/arrow-java#466]
### Describe the bug, including details regarding any error messages, version, and platform.

- org.apache.arrow.flight.grpc isn't exported
- JDBC driver uses 'flight.sql.jdbc.core' which doesn't match other packages like 'org.apache.arrow.flight.core'

**Comment by lidavidm** [comment]
So it seems we can't fix the automatic module name for the JDBC driver since Avatica is packaged in a way that it can't become an automatic module :/

**Comment by wgtmac** [comment]
> So it seems we can't fix the automatic module name for the JDBC driver since Avatica is packaged in a way that it can't become an automatic module :/

Is it because Avatica is shaded with package name transformed? (It might be a dumb question since I'm still new to JPMS).

**Comment by lidavidm** [comment]
I didn't save the error but IIRC it had to do with service providers
