### ISSUE TITLE
[Java] Allow Arrow API to read file contents from inputStream instead of only Path

### ISSUE THREAD

**Issue by swapnil-bidgely** [apache/arrow-java#47]
### Describe the enhancement requested

Currently, only `uri` is allowed as interface if we wish to read any file format
    
```
public FileSystemDatasetFactory(BufferAllocator allocator, NativeMemoryPool memoryPool, FileFormat format, String uri) {
        super(allocator, memoryPool, createNative(format, uri));
    }
```

I have a usecase where in I would want to pass an inputstream and based on it I wished to read and convert to the target fileformat. 
Could someone from the community help me with this requirement, as this would help me go away from ParquetReader library or even AvroReader library and use Arrow instead
    
    

### Component(s)

Java

**Comment by assignUser** [comment]
@lidavidm comment sounds like this wont' happen for technical reasons.
